/*
 * generated by Xtext
 */
package org.eclipse.gef.dot.internal.language;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DotPortPosStandaloneSetup extends DotPortPosStandaloneSetupGenerated{

	public static void doSetup() {
		new DotPortPosStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

